### PR TITLE
Added alerts for invalid move operations:

### PR DESCRIPTION
**Pull request by moorear**
**Alerts When:**
-when a card is moved to a non-empty column
-when a non-Ace card is moved to an empty column

### CODE REVIEW

**Comment by DavidSahni** [comment]
So testing this on my computer, the rules work correctly however I am not getting the alerts from the joptionpane. Since this seems inconsistent/kinda weird, I would keep the same structure but instead of using joptionpane, mark a public variable in the game class (boolean moveGood or something) on whether a move was correct or not. Then in the javascript, check if moveGood is true and use alert("bad move") if its not

**Comment by moorear** [comment]
Thanks for the help David! I implemented the public boolean in the Game Class so that we can check in the javascript if an invalid move occurred and directly alert() the user.

**Comment by DavidSahni** [comment]
Looking good, one minuscule thing, the javascript check should probably go after the ajax call so that we don't alert people when they do correct moves!

**Comment by DavidSahni** [comment]
Alright looks good! With the validMove check inside the ajax success function, everything should work correctly and run when it should!

**Pull request merged**
